AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # DynamoDB Table
  ScoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ScoresTable
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ScoresTable.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  # Lambda Function
  ScoreCalculatorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ScoreCalculatorFunction
      Runtime: python3.13
      Handler: handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import math
          import boto3
          import os
          import json

          dynamodb = boto3.resource('dynamodb')
          table_name = os.getenv('DYNAMODB_TABLE', 'ScoresTable')
          table = dynamodb.Table(table_name)

          def calculate_score(success_count, elapsed_seconds):
              if elapsed_seconds <= 0:
                  return 0
              raw_score = success_count / elapsed_seconds
              score = math.log(1 + raw_score) * 100
              return round(score, 2)

          def lambda_handler(event, context):
              try:
                  username = event['username']
                  elapsed_seconds = event['elapsed_seconds']
                  success_count = event['success_count']

                  score = calculate_score(success_count, elapsed_seconds)

                  payload = {
                      'username': username,
                      'elapsed_seconds': elapsed_seconds,
                      'success_count': success_count,
                      'score': score
                  }

                  table.put_item(Item=payload)

                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Score calculated and stored successfully.',
                          'score': score
                      })
                  }
              except Exception as e:
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'message': 'An error occurred.',
                          'error': str(e)
                      })
                  }
      Environment:
        Variables:
          DYNAMODB_TABLE: ScoresTable

  # Lambda URL
  LambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt ScoreCalculatorLambda.Arn

Outputs:
  LambdaUrlEndpoint:
    Description: "The URL endpoint for the Lambda function"
    Value: !GetAtt LambdaUrl.FunctionUrl
  DynamoDBTableName:
    Description: "The name of the DynamoDB table"
    Value: !Ref ScoresTable
  LambdaFunctionName:
    Description: "The name of the Lambda function"
    Value: !Ref ScoreCalculatorLambda
